#!/usr/bin/env bash
set -euo pipefail

DISK=${1:-/dev/vda}
EFI_PART="${DISK}1"
LUKS_PART="${DISK}2"

sgdisk --zap-all "${DISK}"
sgdisk -n 1:0:+1G -t 1:ef00 -c 1:efiboot "${DISK}"
sgdisk -n 2:0:0 -t 2:8309 -c 2:cryptroot "${DISK}"
sync && udevadm settle

echo "--> Setting up LUKS on ${LUKS_PART}"
cryptsetup -c aes-xts-plain64 -s 512 -h sha512 -i 2000 --use-random \
  --label=LUKS luksFormat --type luks2 "${LUKS_PART}"
cryptsetup open --type luks "${LUKS_PART}" cryptroot

pvcreate /dev/mapper/cryptroot
vgcreate nixos /dev/mapper/cryptroot
lvcreate -L 4G -n swap nixos
lvcreate -l '100%FREE' -n root nixos

mkfs.vfat -n BOOT -F32 "${EFI_PART}"
mkfs.ext4 -L root /dev/mapper/nixos-root
mkswap -L swap /dev/mapper/nixos-swap

mount /dev/mapper/nixos-root /mnt
mkdir -p /mnt/boot
mount -o umask=0077 "${EFI_PART}" /mnt/boot
swapon /dev/mapper/nixos-swap

vgscan
vgchange -ay
lsblk -o name,type,mountpoints /dev/vda
