#!/usr/bin/env bash
set -euo pipefail

clone_config() {
  echo "--> Installing NixOS from flake"
  git clone https://github.com/pervezfunctor/nixos-remote.git /mnt/etc/nixos
}

install_nixos() {
  mkdir -p /mnt/etc/ssh
  ssh-keygen -t ed25519 -f /mnt/etc/ssh/ssh_host_ed25519_key -N ""
  chmod 600 /mnt/etc/ssh/ssh_host_ed25519_key
  nixos-install --root /mnt --no-root-passwd --flake /mnt/etc/nixos#ilm
  nixos-enter --root /mnt -c 'passwd pervez'
}

cleanup() {
  echo "--- Installation Complete ---"
  umount -R /mnt
  swapoff /dev/mapper/nixos-swap
  vgchange -a n nixos
  cryptsetup close /dev/mapper/cryptroot
  echo "--- You can now reboot. ---"
}

main() {
  clone_config
  install_nixos
  cleanup
}

main
