#!/usr/bin/env bash
set -euo pipefail

if [ "$(id -u)" -ne 0 ]; then
  echo "❌ This script must be run as root" >&2
  exit 1
fi

# @TODO: Only copy configuration.nix and flake.nix instead?
clone_config() {
  if [ ! -d /mnt ]; then
    echo "❌ /mnt does not exist" >&2
    exit 1
  fi
  echo "--> Installing NixOS from flake"
  git clone https://github.com/mefunctor/nixos-remote.git /mnt/etc/nixos
}

setup_ssh_key() {
  [ ! -d /mnt/etc/ssh ] && mkdir -p /mnt/etc/ssh

  if [ ! -f /mnt/etc/ssh/ssh_host_ed25519_key ]; then
    ssh-keygen -t ed25519 -f /mnt/etc/ssh/ssh_host_ed25519_key -N ""
  fi

  chmod 600 /mnt/etc/ssh/ssh_host_ed25519_key
}

install_nixos() {
  nixos-install --root /mnt --no-root-passwd --flake /mnt/etc/nixos#ilm
  nixos-enter --root /mnt -c 'passwd me'
}

cleanup() {
  echo "--- Installation Complete ---"
  umount -R /mnt
  swapoff /dev/mapper/nixos-swap
  vgchange -a n nixos
  cryptsetup close /dev/mapper/cryptroot
  echo "--- You can now reboot. ---"
}

main() {
  clone_config
  setup_ssh_key
  install_nixos
  cleanup
}

main
