#! /bin/bash

download_iso() {
  if [ ! -f /var/lib/libvirt/images/nixos-minimal-25.05.iso ]; then
    echo "Downloading NixOS ISO"
    sudo wget https://channels.nixos.org/nixos-25.05/latest-nixos-minimal-x86_64-linux.iso -O /var/lib/libvirt/images/nixos-minimal-25.05.iso
  else
    echo "NixOS ISO already exists"
  fi

}

create_disk() {
  if [ ! -f /var/lib/libvirt/images/nixvm.qcow2 ]; then
    echo "Creating VM disk"
    sudo qemu-img create -f qcow2 /var/lib/libvirt/images/nixvm.qcow2 20G
  else
    echo "VM disk already exists"
  fi

}

get_uefi_paths() {
  local code vars
  if [[ -e /etc/os-release ]]; then
    # shellcheck disable=SC1091
    . /etc/os-release

    case "$ID" in
    fedora | rhel)
      code="/usr/share/edk2/ovmf/OVMF_CODE.fd"
      vars="/usr/share/edk2/ovmf/OVMF_VARS.fd"
      ;;
    ubuntu | debian)
      code="/usr/share/OVMF/OVMF_CODE.fd"
      vars="/usr/share/OVMF/OVMF_VARS.fd"
      ;;
    arch)
      code="/usr/share/edk2-ovmf/x64/OVMF_CODE.fd"
      vars="/usr/share/edk2-ovmf/x64/OVMF_VARS.fd"
      ;;
    opensuse* | suse | tumbleweed)
      # SMM, non-SecureBoot variant — best for NixOS
      code="/usr/share/qemu/ovmf-x86_64-smm-5m-code.bin"
      vars="/usr/share/qemu/ovmf-x86_64-smm-vars.bin"
      ;;
    *)
      echo "❌ Unknown or unsupported distro: $ID" >&2
      exit 1
      ;;
    esac
  else
    echo "❌ Cannot detect host OS." >&2
    exit 1
  fi
  echo "$code|$vars"
}

IFS="|" read -r OVMF_CODE OVMF_VARS < <(get_uefi_paths)

# NEED THIS?
# DISK_PATH="/var/lib/libvirt/images/${VM_NAME}.qcow2"
# NVRAM_PATH="/var/lib/libvirt/qemu/nvram/${VM_NAME}_VARS.fd"
# # Copy and prepare NVRAM for the VM
# sudo mkdir -p "$(dirname "$NVRAM_PATH")"
# sudo cp "$OVMF_VARS" "$NVRAM_PATH"
# sudo chown libvirt-qemu:kvm "$NVRAM_PATH"
# sudo chmod 644 "$NVRAM_PATH"

create_vm() {
  if virsh list --all | grep -q nixvm; then
    echo "VM already exists"
    return 0
  fi

  echo "Creating VM"
  virt-install \
    --cpu host \
    --machine q35 \
    --disk path="$DISK_PATH",size="$DISK_SIZE",format=qcow2 \
    --name nixvm \
    --memory 8192 \
    --vcpus 4 \
    --disk path=/var/lib/libvirt/images/nixvm.qcow2,format=qcow2 \
    --cdrom /var/lib/libvirt/images/nixos-minimal-25.05.iso \
    --network network=default \
    --os-variant nixos-unstable \
    --graphics spice \
    --boot loader="$OVMF_CODE" \
    --nvram "$OVMF_VARS"

  # Tested below to work on fedora
  # --boot loader=/usr/share/OVMF/OVMF_CODE.fd,loader_ro=yes,loader_type=pflash,nvram_template=/usr/share/OVMF/OVMF_VARS.fd
}

eject_iso() {
  virsh change-media nixvm hda --eject --config
}

get_ip() {
  virsh net-dhcp-leases default | grep nixvm | awk '{print $5}' | cut -d/ -f1
}

main() {
  download_iso
  create_vm
  eject_iso

  echo "VM created. You can now ssh to it with the following command:"
  echo "ssh root@$(get_ip)"
}

main
