#! /usr/bin/env bash

CONFIG=${1:-vm}

# if flakes is enabled, then
nix build .#nixosConfigurations.vm.config.system.build."${CONFIG}"

# if flakes is not enabled, then
#nixos-rebuild build-vm -I nixos-config="${CONFIG}" # or
#nix-build '<nixpkgs/nixos>' -A config.system.build.vm -I nixos-config="${CONFIG}"
